git:
  submodules: true
language: scala
# run on new infrastructure
sudo: false

cache:
  directories:
    $HOME/.ivy2
    $INSTALL_DIR

env:
  global:
    INSTALL_DIR=$TRAVIS_BUILD_DIR/install
    VERILATOR_ROOT=$INSTALL_DIR
    PATH=$PATH:$VERILATOR_ROOT/bin:$TRAVIS_BUILD_DIR/utils/bin

install:
  - bash .install_verilator.sh
  - verilator --version

script:
  - set -o pipefail && sbt awl/test
  - set -o pipefail && sbt rocket-awl/test

